apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-fs-volume 
spec:
  capacity:
    storage: 1Ti
  nfs:
    path: /vol01
    server: 10.127.168.234
  accessModes:
    - ReadWriteMany # Sharabale storage
  persistentVolumeReclaimPolicy: Retain 
  claimRef:
    name: manual-fs-vol-claim
    namespace: default
