apiVersion: v1 
kind: ResourceQuota
metadata:
  name: devops-team-ns-quota 
  namespace: devops-team 
spec:
  hard:
    requests.cpu: "1"         #minimum
    requests.memory: "1Gi"
    limits.cpu: "2"           #maximum
    limits.memory: "2Gi"
    pods: "10"