apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-log-role-binding
subjects:
- kind: User
  name: nextops.t28@gmail.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: pod-log-reader
  apiGroup: rbac.authorization.k8s.io