apiVersion: apps/v1
kind: Deployment #Controller
metadata:
  name: httpd-deploy
  labels:
    app: httpd
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: httpd  
  template:
    metadata:
      name: simple-pod
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: httpd:latest
          ports:
            - containerPort: 80