#for simulating alterrule use this yaml
apiVersion: v1
kind: Pod
metadata:
  name: pending-pod-example
spec:
  containers:
    - name: resource-hungry-container
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "1000Mi" #Requesting high memory
          cpu: "1000m"  #Requesting high cpu