apiVersion: v1 
kind: Secret 
metadata: 
  name: mongodb-secret 
data:
  mongodb-root-username: YWRtaW4=       #admin
  mongodb-root-password: cGFzczEyMw==   #pass123
  mongo-web-username: d2ViYWRtaW4=      #webadmin
  mongo-web-password: d2VicGFzczEyMw==  #webpass123
type: Opaque